find_package(OpenGLES2 QUIET)
find_package(OpenGLES3 QUIET)

if(OpenGLES2_FOUND OR OpenGLES3_FOUND)
    if(OPENGLES3_INCLUDE_DIR AND OPENGLES3_LIBRARIES)
        message(STATUS "Found GLESv3: ${OPENGLES3_LIBRARIES}")
        add_definitions(-DGLES3)
        set(GLES_LIB ${OPENGLES3_LIBRARIES})
        set(GLES_INCLUDE ${OPENGLES3_INCLUDE_DIR})
    elseif(OPENGLES2_INCLUDE_DIR AND OPENGLES2_LIBRARIES)
        message(STATUS "Found GLESv2: ${OPENGLES2_LIBRARIES}")
        add_definitions(-DGLES2)
        set(GLES_LIB ${OPENGLES2_LIBRARIES})
        set(GLES_INCLUDE ${OPENGLES2_INCLUDE_DIR})
    else()
        message(FATAL_ERROR "Neither GLESv2 nor GLESv3 found")
    endif()
else()
    message(FATAL_ERROR "OpenGL package not found")
endif()

mark_as_advanced(GLES_INCLUDE GLES_LIB)